---
- name: create frontend dir
  file: dest={{atlas_frontend_path}} owner={{atlas_webuser}} group={{atlas_webuser}} state=directory recurse=yes

- name: get frontend code
  git: repo={{atlas_frontend_git_repo}}
       dest={{atlas_frontend_path}}
       version={{atlas_frontend_git_version}}
       depth=1
       accept_hostkey=true
  sudo_user: "{{atlas_webuser}}"

- name: install sass
  gem: name=sass state=latest

- name: install ember
  npm: name=ember-cli version=0.2.7 global=yes

- name: install grunt-cli
  npm: name=grunt-cli version=0.1.13 global=yes

- name: install bower
  npm: name=bower version=1.4.1 global=yes

- name: Install frontend packages based on package.json.
  npm: path={{atlas_frontend_path}}
  sudo_user: "{{atlas_webuser}}"

- name: bower unlink vis-toolkit
  shell: "bower unlink vis-toolkit"
  args:
      chdir: "{{atlas_frontend_path}}"
  sudo_user: "{{atlas_webuser}}"

- name: Install packages based on bower.json.
  shell: "bower install"
  args:
      chdir: "{{atlas_frontend_path}}"
  #bower: path={{atlas_frontend_path}}
  sudo_user: "{{atlas_webuser}}"

- name: get vis-toolkit code
  git: repo={{atlas_vistk_git_repo}}
       dest={{atlas_vistk_path}}
       version={{atlas_vistk_git_version}}
       accept_hostkey=true
  sudo_user: "{{atlas_webuser}}"

- name: bower link
  shell: "bower link"
  args:
      chdir: "{{atlas_vistk_path}}"
  sudo_user: "{{atlas_webuser}}"

- name: bower link vis-toolkit
  shell: "bower link vis-toolkit"
  args:
      chdir: "{{atlas_frontend_path}}"
  sudo_user: "{{atlas_webuser}}"

- name: ember build
  shell: "cd {{atlas_frontend_path}}; ember build --environment=production"
  args:
      chdir: "{{atlas_frontend_path}}"
  environment: "{{atlas_ember_environment}}"
  sudo_user: "{{atlas_webuser}}"
